---
title: ""
subtitle: ""
author: ""
date: "`r format(Sys.Date(), '%B %e, %Y')`"
urlcolor: "blue"
output:
  bookdown::html_document2:
    number_sections: no
    self_contained: false
    toc: no
    toc_depth: 2
    toc_float:
      collapsed: yes
    css: html/style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.dim = c(7, 4),
	out.width = '100%',
	dev = 'svg'
)
```


```{r}
library(dplyr)
data <- readr::read_csv('network_attributes.csv') %>% 
  filter(Id != '牙醫學系')
data$transfer_group <- as.factor(data$groups_transfer)
```

```{r}
library(ggplot2)
library(ggrepel)
plot_xy <- function(data, x, y, 
                    xlab = '工作變動性 (2-5 年 vs. 5-10 年)',
                    ylab = '轉系網絡 PageRank') {
  pl <- ggplot(data, 
               aes(x = x, y = y)) +
    geom_point(aes(color = college), size = 0.5) +
    geom_smooth(se = F, formula = y~x, method='lm', 
                size=0.4, alpha = 0.8, color='grey') +
    geom_text_repel(aes(label = Id, color = college), 
            size = 1.6, segment.size = 0.15) +
    labs(x = xlab, #'工作變動性 (2-5 年 vs. 5-10 年)'
         y = ylab) +  #轉系網絡之 PageRank
    theme(legend.position = "none")
}
```

## In-degree

```{r}
plot_xy(data, x = data$`job_1st-2nd`, y = data$indegree,
        xlab = '工作變動性 (1st Job vs. 2-5 年)',
        ylab = '轉系網絡 In-degree') %>% print()
```


```{r}
plot_xy(data, x = data$`job_2nd-3rd`, y = data$indegree,
        xlab = '工作變動性 (2-5 年 vs. 5-10 年)',
        ylab = '轉系網絡 In-degree') %>% print()
```


```{r}
plot_xy(data, x = data$`industr_1st-2nd`, y = data$indegree,
        xlab = '產業變動性 (1st Job vs. 5-10 年)',
        ylab = '轉系網絡 In-degree') %>% print()
```


```{r}
plot_xy(data, x = data$`industr_2nd-3rd`, y = data$indegree,
        xlab = '產業變動性 (2-5 年 vs. 5-10 年)',
        ylab = '轉系網絡 In-degree') %>% print()
```


## Out-degree

```{r}
plot_xy(data, x = data$`job_1st-2nd`, y = data$outdegree,
        xlab = '工作變動性 (1st Job vs. 2-5 年)',
        ylab = '轉系網絡 Out-degree') %>% print()
```

```{r}
plot_xy(data, x = data$`job_2nd-3rd`, y = data$outdegree,
        xlab = '工作變動性 (2-5 年 vs. 5-10 年)',
        ylab = '轉系網絡 Out-degree') %>% print()
```


```{r}
plot_xy(data, x = data$`industr_1st-2nd`, y = data$outdegree,
        xlab = '產業變動性 (1st Job vs. 2-5 年)',
        ylab = '轉系網絡 Out-degree') %>% print()
```


```{r}
plot_xy(data, x = data$`industr_2nd-3rd`, y = data$outdegree,
        xlab = '產業變動性 (2-5 年 vs. 5-10 年)',
        ylab = '轉系網絡 Out-degree') %>% print()
```


## 工作類別變動性 vs. PageRank

```{r}
plot_xy(data, data$`job_1st-2nd`, data$transfer_group,
          xlab = '工作變動性 (1st Job vs. 2-5 年)') %>% print()
```

```{r}
plot_xy(data, data$`job_2nd-3rd`, data$transfer_pageranks) %>% print()
```

## 產業類別變動性 vs. PageRank

```{r}
plot_xy(data, data$`industr_1st-2nd`, data$transfer_pageranks,
        xlab = '產業變動性 (1st Job vs. 2-5 年)') %>% print()
  
```

```{r}
plot_xy(data, data$`industr_2nd-3rd`, data$transfer_pageranks,
        xlab = '產業變動性 (2-5 年 vs. 5-10 年)') %>% print()
```


