---
title: "轉系"
subtitle: ""
author: ""
date: "`r format(Sys.Date(), '%B %e, %Y')`"
urlcolor: "blue"
output:
  bookdown::html_document2:
    number_sections: true
    self_contained: false
    css: html/style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.dim = c(7, 4),
	out.width = '100%',
	dev = 'svg'
)
```


```{r}
library(dplyr)
source('plot_func.R')

data <- readr::read_csv('network_attributes.csv') %>% 
  filter(Id != '牙醫學系')
data$transfer_group <- as.factor(data$groups_transfer)
```


## In-degree

```{r}
plot_xy(data, x = data$`job_1st-2nd`, y = data$transfer_indegree,
        xlab = '工作變動性 (1st Job vs. 2-5 年)',
        ylab = '轉系網絡 In-degree') %>% print()
```


```{r}
plot_xy(data, x = data$`job_2nd-3rd`, y = data$transfer_indegree,
        xlab = '工作變動性 (2-5 年 vs. 5-10 年)',
        ylab = '轉系網絡 In-degree') %>% print()
```


```{r}
plot_xy(data, x = data$`industr_1st-2nd`, y = data$transfer_indegree,
        xlab = '產業變動性 (1st Job vs. 5-10 年)',
        ylab = '轉系網絡 In-degree') %>% print()
```


```{r}
cor2 <- round(cor(data$`industr_2nd-3rd`, data$transfer_indegree), 3)
```

(ref:cor-indegree) 相關係數：`r cor2`

```{r fig.cap='(ref:cor-indegree)'}
plot_xy(data, x = data$`industr_2nd-3rd`, y = data$transfer_indegree,
        xlab = '產業變動性 (2-5 年 vs. 5-10 年)',
        ylab = '轉系網絡 In-degree') %>% print()
```


## Out-degree

```{r}
plot_xy(data, x = data$`job_1st-2nd`, y = data$transfer_outdegree,
        xlab = '工作變動性 (1st Job vs. 2-5 年)',
        ylab = '轉系網絡 Out-degree') %>% print()
```

```{r}
plot_xy(data, x = data$`job_2nd-3rd`, y = data$transfer_outdegree,
        xlab = '工作變動性 (2-5 年 vs. 5-10 年)',
        ylab = '轉系網絡 Out-degree') %>% print()
```


```{r}
plot_xy(data, x = data$`industr_1st-2nd`, y = data$transfer_outdegree,
        xlab = '產業變動性 (1st Job vs. 2-5 年)',
        ylab = '轉系網絡 Out-degree') %>% print()
```


```{r}
plot_xy(data, x = data$`industr_2nd-3rd`, y = data$transfer_outdegree,
        xlab = '產業變動性 (2-5 年 vs. 5-10 年)',
        ylab = '轉系網絡 Out-degree') %>% print()
```


## PageRank

```{r}
plot_xy(data, data$`job_1st-2nd`, data$transfer_pageranks,
          xlab = '工作變動性 (1st Job vs. 2-5 年)') %>% print()
```

```{r}
plot_xy(data, data$`job_2nd-3rd`, data$transfer_pageranks,
        xlab = '工作變動性 (2-5 年 vs. 5-10 年)') %>% print()
```


```{r}
plot_xy(data, data$`industr_1st-2nd`, data$transfer_pageranks,
        xlab = '產業變動性 (1st Job vs. 2-5 年)') %>% print()
  
```


```{r}
cor2 <- round(cor(data$`industr_2nd-3rd`, data$transfer_pageranks), 3)
```

(ref:cor-page) 相關係數：`r cor2`

```{r fig.cap='(ref:cor-page)'}
plot_xy(data, data$`industr_2nd-3rd`, data$transfer_pageranks,
        xlab = '產業變動性 (2-5 年 vs. 5-10 年)') %>% print()
```


